### ISSUE TITLE
How to launch it?

### ISSUE THREAD

**Issue by NoxInfinity1** [Furimanejo/Buttplug-Of-Legends-Unity#1]
Hi, sorry in advance I'm a big noob so I didn't understand how to throw it. Could you explain me or give me some clue?
ty :)

**Comment by Furimanejo** [comment]
Download the latest build (https://github.com/Furimanejo/Buttplug-Of-Legends-Unity/releases), extract it in a folder and run the ButtplugOfLegendsUnity.exe

**Comment by NoxInfinity1** [comment]
Oh okay thanks ^^ I feel stupid. Sorry I don't know Github :)

**Comment by Furimanejo** [comment]
No worries
